[workspace]
resolver = "3"
members = ["crates/*/"]
default-members = ["crates/mulan-cli/"]

[workspace.package]
version = "0.0.0"
description = "A multi-language i18n framework"
readme = true
repository = "https://github.com/asqarslanov/mulan"
license-file = "LICENSE"
keywords = [
  "cli",
  "framework",
  "i18n",
  "internationalization",
  "intl",
  "l10n",
  "localization",
  "mulan",
]
categories = [
  "command-line-utilities",
  "development-tools",
  "internationalization",
  "localization",
]
publish = false

[workspace.dependencies]
chumsky = "0.13.0"
clap = "4.6.5"
compact_str = "0.10.0"
figment2 = "0.11.5"
foldhash = "0.2.0"
indoc = "2.0.7"
itertools = "0.15.0"
miette = "7.6.0"
mitsein = {
  git = "https://github.com/asqarslanov/mitsein.git",
  branch = "compact-str",
}
mulan-config = { path = "crates/mulan-config/" }
mulan-parser = { path = "crates/mulan-parser/" }
pathdiff = "0.2.3"
relative-path = "2.0.1"
rstest = "0.26.1"
serde = "1.0.229"
serde-saphyr = "0.0.29"
serde_with = "3.21.0"
serdev = "0.3.2"
smallvec = "1.15.2"
strum = "0.28.0"
tempfile = "3.27.0"
thiserror = "2.0.19"
toml = { version = "1.1.4", features = ["fast_hash"] }

[workspace.lints.clippy]
all = "warn"
missing-errors-doc = { level = "allow", priority = 1 }
missing-panics-doc = { level = "allow", priority = 1 }
nursery = "warn"
pedantic = "warn"

[profile.release]
opt-level = "z"
strip = true
lto = true
panic = "abort"
codegen-units = 1
