[package]
name = "mulan-gen"
version.workspace = true
edition = "2024"
description.workspace = true
readme.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
aho-corasick = { workspace = true }
compact_str = { workspace = true }
indent = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
mitsein = { workspace = true }
mulan-config = { workspace = true }
mulan-parser = { workspace = true }

[lints]
workspace = true
