[package]
name = "mulan-parser"
version.workspace = true
edition = "2024"
description.workspace = true
readme.workspace = true
repository.workspace = true
license-file.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[dependencies]
chumsky = { workspace = true }
compact_str = { workspace = true }
serde = { workspace = true, features = ["derive"] }
smallvec = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[lints]
workspace = true
