[package]
name = "mulan"
version.workspace = true
description.workspace = true
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.5.19", features = ["cargo", "derive"] }
inquire = "0.7.5"
