// This file is automatically @generated by Mulan.
// It is not intended for manual editing.

//! # Mulan

#![allow(warnings)]

#[rustfmt::skip]

/// - [`EnUs`](Self::EnUs) (main)

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Locale {
    /// en-US / English (United States)
    #[default]
    EnUs,
}

/// The root namespace.
pub mod t {
    use super::Locale;

    /// `cmd-gen`
    pub mod cmd_gen {
        use super::Locale;

        /// `cmd-gen.log`
        ///
        /// ```mulan
        /// Generated {target} bindings in `{path}`
        /// ```
        #[must_use]
        pub struct Log<'path, 'target> {
            pub path: &'path str,
            pub target: &'target str,
        }

        impl Log<'_, '_> {
            #[must_use]
            pub fn get_in(&self, locale: Locale) -> String {
                match locale {
                    _ => format!(
                        "Generated {target} bindings in `{path}`",
                        path = self.path,
                        target = self.target
                    ),
                }
            }
        }
    }
}
