// This file is automatically @generated by Mulan.
// It is not intended for manual editing.

//! # Mulan

#![allow(warnings)]

#[rustfmt::skip]

/// - [`EnUs`](Self::EnUs) (main)
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Locale {
    /// en-US / English (United States)
    #[default]
    EnUs,
}

/// The root namespace.
pub mod t {
    use super::Locale;

    /// `cmd-gen`
    pub mod cmd_gen {
        use super::Locale;

        /// `cmd-gen.log`
        ///
        /// ```mulan
        /// Generated {target} bindings in `{path}`
        /// ```
        #[must_use]
        pub struct Log<'path, 'target> {
            pub path: &'path str,
            pub target: &'target str,
        }

        impl Log<'_, '_> {
            #[must_use]
            pub fn get_in(&self, locale: Locale) -> String {
                match locale {
                    _ => format!("Generated {target} bindings in `{path}`", path = self.path, target = self.target),
                }
            }
        }
    }

    /// `errors`
    pub mod errors {
        use super::Locale;

        /// `errors.config`
        pub mod config {
            use super::Locale;

            /// `errors.config.ambiguous-source`
            pub mod ambiguous_source {
                use super::Locale;

                /// `errors.config.ambiguous-source.help`
                ///
                /// ```mulan
                /// only choose one config to remain, and delete the other{plural-ending}
                /// ```
                #[must_use]
                pub struct Help<'plural_ending> {
                    pub plural_ending: &'plural_ending str,
                }

                impl Help<'_> {
                    #[must_use]
                    pub fn get_in(&self, locale: Locale) -> String {
                        match locale {
                            _ => format!("only choose one config to remain, and delete the other{plural_ending}", plural_ending = self.plural_ending),
                        }
                    }
                }

                /// `errors.config.ambiguous-source.message`
                ///
                /// ```mulan
                /// multiple possible config locations
                /// ```
                #[must_use]
                pub struct Message;

                impl Message {
                    #[must_use]
                    pub const fn get_in(&self, locale: Locale) -> &'static str {
                        match locale {
                            _ => "multiple possible config locations",
                        }
                    }
                }

                /// `errors.config.ambiguous-source.annotation-block`
                pub mod annotation_block {
                    use super::Locale;

                    /// `errors.config.ambiguous-source.annotation-block.first-label`
                    ///
                    /// ```mulan
                    /// maybe this?
                    /// ```
                    #[must_use]
                    pub struct FirstLabel;

                    impl FirstLabel {
                        #[must_use]
                        pub const fn get_in(&self, locale: Locale) -> &'static str {
                            match locale {
                                _ => "maybe this?",
                            }
                        }
                    }

                    /// `errors.config.ambiguous-source.annotation-block.other-labels`
                    ///
                    /// ```mulan
                    /// or maybe even this?
                    /// ```
                    #[must_use]
                    pub struct OtherLabels;

                    impl OtherLabels {
                        #[must_use]
                        pub const fn get_in(&self, locale: Locale) -> &'static str {
                            match locale {
                                _ => "or maybe even this?",
                            }
                        }
                    }

                    /// `errors.config.ambiguous-source.annotation-block.second-label`
                    ///
                    /// ```mulan
                    /// or maybe this?
                    /// ```
                    #[must_use]
                    pub struct SecondLabel;

                    impl SecondLabel {
                        #[must_use]
                        pub const fn get_in(&self, locale: Locale) -> &'static str {
                            match locale {
                                _ => "or maybe this?",
                            }
                        }
                    }
                }
            }

            /// `errors.config.current-dir`
            pub mod current_dir {
                use super::Locale;

                /// `errors.config.current-dir.help`
                ///
                /// ```mulan
                /// make sure that
                /// - the current working directory exists
                /// - you have permissions to access it
                /// ```
                #[must_use]
                pub struct Help;

                impl Help {
                    #[must_use]
                    pub const fn get_in(&self, locale: Locale) -> &'static str {
                        match locale {
                            _ => "make sure that\n- the current working directory exists\n- you have permissions to access it",
                        }
                    }
                }

                /// `errors.config.current-dir.message`
                ///
                /// ```mulan
                /// failed to get current working directory
                /// - OS error: {os-error}
                /// ```
                #[must_use]
                pub struct Message<'os_error> {
                    pub os_error: &'os_error str,
                }

                impl Message<'_> {
                    #[must_use]
                    pub fn get_in(&self, locale: Locale) -> String {
                        match locale {
                            _ => format!("failed to get current working directory\n- OS error: {os_error}", os_error = self.os_error),
                        }
                    }
                }
            }

            /// `errors.config.not-found`
            pub mod not_found {
                use super::Locale;

                /// `errors.config.not-found.help`
                ///
                /// ```mulan
                /// make sure you're inside your project that uses Mulan
                /// or run `mulan init` to get started

                /// Mulan is an i18n framework
                /// more info: <https://github.com/asqarslanov/mulan>
                /// ```
                #[must_use]
                pub struct Help;

                impl Help {
                    #[must_use]
                    pub const fn get_in(&self, locale: Locale) -> &'static str {
                        match locale {
                            _ => "make sure you\'re inside your project that uses Mulan\nor run `mulan init` to get started\n\nMulan is an i18n framework\nmore info: <https://github.com/asqarslanov/mulan>",
                        }
                    }
                }

                /// `errors.config.not-found.message`
                ///
                /// ```mulan
                /// Mulan config not found in any parent dirctory
                /// ```
                #[must_use]
                pub struct Message;

                impl Message {
                    #[must_use]
                    pub const fn get_in(&self, locale: Locale) -> &'static str {
                        match locale {
                            _ => "Mulan config not found in any parent dirctory",
                        }
                    }
                }
            }

            /// `errors.config.parse`
            pub mod parse {
                use super::Locale;

                /// `errors.config.parse.invalid-type`
                pub mod invalid_type {
                    use super::Locale;

                    /// `errors.config.parse.invalid-type.message`
                    ///
                    /// ```mulan
                    /// invalid type
                    ///   key `{key}`
                    ///   is expected to be `{expected}`
                    ///   but actually has type `{actual}`
                    /// ```
                    #[must_use]
                    pub struct Message<'actual, 'expected, 'key> {
                        pub actual: &'actual str,
                        pub expected: &'expected str,
                        pub key: &'key str,
                    }

                    impl Message<'_, '_, '_> {
                        #[must_use]
                        pub fn get_in(&self, locale: Locale) -> String {
                            match locale {
                                _ => format!("invalid type\n  key `{key}`\n  is expected to be `{expected}`\n  but actually has type `{actual}`", actual = self.actual, expected = self.expected, key = self.key),
                            }
                        }
                    }
                }

                /// `errors.config.parse.unknown-field`
                pub mod unknown_field {
                    use super::Locale;

                    /// `errors.config.parse.unknown-field.help`
                    ///
                    /// ```mulan
                    /// maybe, you mistyped it?
                    /// ```
                    #[must_use]
                    pub struct Help;

                    impl Help {
                        #[must_use]
                        pub const fn get_in(&self, locale: Locale) -> &'static str {
                            match locale {
                                _ => "maybe, you mistyped it?",
                            }
                        }
                    }

                    /// `errors.config.parse.unknown-field.message`
                    ///
                    /// ```mulan
                    /// unknown field: `{actual}`
                    /// ```
                    #[must_use]
                    pub struct Message<'actual> {
                        pub actual: &'actual str,
                    }

                    impl Message<'_> {
                        #[must_use]
                        pub fn get_in(&self, locale: Locale) -> String {
                            match locale {
                                _ => format!("unknown field: `{actual}`", actual = self.actual),
                            }
                        }
                    }
                }

                /// `errors.config.parse.unknown-variant`
                pub mod unknown_variant {
                    use super::Locale;

                    /// `errors.config.parse.unknown-variant.message`
                    ///
                    /// ```mulan
                    /// unknown variant
                    ///   key `{key}`
                    ///   is{actual}
                    ///   but is expected to be one of: {expected}
                    /// ```
                    #[must_use]
                    pub struct Message<'actual, 'expected, 'key> {
                        pub actual: &'actual str,
                        pub expected: &'expected str,
                        pub key: &'key str,
                    }

                    impl Message<'_, '_, '_> {
                        #[must_use]
                        pub fn get_in(&self, locale: Locale) -> String {
                            match locale {
                                _ => format!("unknown variant\n  key `{key}`\n  is{actual}\n  but is expected to be one of: {expected}", actual = self.actual, expected = self.expected, key = self.key),
                            }
                        }
                    }
                }
            }
        }

        /// `errors.parser`
        pub mod parser {
            use super::Locale;

            /// `errors.parser.read`
            pub mod read {
                use super::Locale;

                /// `errors.parser.read.fs`
                pub mod fs {
                    use super::Locale;

                    /// `errors.parser.read.fs.help`
                    ///
                    /// ```mulan
                    /// make sure that
                    /// - {path} exists
                    /// - it contains valid UTF-8
                    /// - you have permissions to read it
                    /// ```
                    #[must_use]
                    pub struct Help<'path> {
                        pub path: &'path str,
                    }

                    impl Help<'_> {
                        #[must_use]
                        pub fn get_in(&self, locale: Locale) -> String {
                            match locale {
                                _ => format!("make sure that\n- {path} exists\n- it contains valid UTF-8\n- you have permissions to read it", path = self.path),
                            }
                        }
                    }

                    /// `errors.parser.read.fs.message`
                    ///
                    /// ```mulan
                    /// failed to read {path}
                    /// OS error: {os-error}
                    /// ```
                    #[must_use]
                    pub struct Message<'os_error, 'path> {
                        pub os_error: &'os_error str,
                        pub path: &'path str,
                    }

                    impl Message<'_, '_> {
                        #[must_use]
                        pub fn get_in(&self, locale: Locale) -> String {
                            match locale {
                                _ => format!("failed to read {path}\nOS error: {os_error}", os_error = self.os_error, path = self.path),
                            }
                        }
                    }
                }

                /// `errors.parser.read.yaml`
                pub mod yaml {
                    use super::Locale;

                    /// `errors.parser.read.yaml.annotation-block`
                    pub mod annotation_block {
                        use super::Locale;

                        /// `errors.parser.read.yaml.annotation-block.here`
                        ///
                        /// ```mulan
                        /// here
                        /// ```
                        #[must_use]
                        pub struct Here;

                        impl Here {
                            #[must_use]
                            pub const fn get_in(&self, locale: Locale) -> &'static str {
                                match locale {
                                    _ => "here",
                                }
                            }
                        }
                    }

                    /// `errors.parser.read.yaml.duplicate-mapping-key`
                    pub mod duplicate_mapping_key {
                        use super::Locale;

                        /// `errors.parser.read.yaml.duplicate-mapping-key.help`
                        ///
                        /// ```mulan
                        /// remove duplicates to make all keys in the same namespace unique
                        /// ```
                        #[must_use]
                        pub struct Help;

                        impl Help {
                            #[must_use]
                            pub const fn get_in(&self, locale: Locale) -> &'static str {
                                match locale {
                                    _ => "remove duplicates to make all keys in the same namespace unique",
                                }
                            }
                        }

                        /// `errors.parser.read.yaml.duplicate-mapping-key.message`
                        ///
                        /// ```mulan
                        /// duplicate mapping key{key}
                        /// ```
                        #[must_use]
                        pub struct Message<'key> {
                            pub key: &'key str,
                        }

                        impl Message<'_> {
                            #[must_use]
                            pub fn get_in(&self, locale: Locale) -> String {
                                match locale {
                                    _ => format!("duplicate mapping key{key}", key = self.key),
                                }
                            }
                        }
                    }
                }
            }

            /// `errors.parser.validate`
            pub mod validate {
                use super::Locale;

                /// `errors.parser.validate.invalid-key`
                pub mod invalid_key {
                    use super::Locale;

                    /// `errors.parser.validate.invalid-key.help`
                    ///
                    /// ```mulan
                    /// it should look like a variable in a programming language
                    /// ```
                    #[must_use]
                    pub struct Help;

                    impl Help {
                        #[must_use]
                        pub const fn get_in(&self, locale: Locale) -> &'static str {
                            match locale {
                                _ => "it should look like a variable in a programming language",
                            }
                        }
                    }

                    /// `errors.parser.validate.invalid-key.message`
                    ///
                    /// ```mulan
                    /// found invalid key
                    ///   locale: {locale}
                    ///   {parent-key}
                    /// ```
                    #[must_use]
                    pub struct Message<'locale, 'parent_key> {
                        pub locale: &'locale str,
                        pub parent_key: &'parent_key str,
                    }

                    impl Message<'_, '_> {
                        #[must_use]
                        pub fn get_in(&self, locale: Locale) -> String {
                            match locale {
                                _ => format!("found invalid key\n  locale: {locale}\n  {parent_key}", locale = self.locale, parent_key = self.parent_key),
                            }
                        }
                    }
                }
            }
        }
    }
}
