//! # Mulan Gen
//!
//! ...

use indoc::indoc;

pub mod rust;

const AUTO_GENERATED_COMMENT: &str = indoc! {"
    This file is automatically @generated by Mulan.
    It is not intended for manual editing.\
"};
