//! # Mulan Gen
//!
//! Generates bindings for various platforms.
//!
//! For now, only [`mod@rust`] is supported.

use indoc::indoc;

pub mod rust;

const AUTO_GENERATED_COMMENT: &str = indoc! {"
    This file is automatically @generated by Mulan.
    It is not intended for manual editing.\
"};
