//! # Mulan Gen
//!
//! Generates i18n bindings for various targets.
//!
//! See the [`write_files`] function.

use std::fs;

use indoc::indoc;

use crate::errors::{CreateDirError, GenError, NoTargetsError, WriteFileError};

pub mod errors;
mod rust;

/// Generates i18n bindings for all platforms specified in the config
/// and writes them to their corresponding files.
pub fn write_files(
    config: &mulan_config::Config,
    bundle: &mulan_parser::Bundle,
) -> Result<(), GenError> {
    let Some(targets) = &config.generate else {
        return Err(GenError::NoTargets(NoTargetsError));
    };
    for target in targets {
        use mulan_config::Target as T;
        let (relative_path, contents) = match target {
            T::Rust(target_conf) => (&target_conf.file, self::rust::generate(config, bundle)),
        };
        if let Some(parent) = relative_path.parent() {
            let file_parent_dir_path = parent.to_path(config.meta.root_dir.as_str());
            fs::create_dir_all(&file_parent_dir_path).map_err(|error| {
                GenError::CreateDir(CreateDirError {
                    error,
                    path: file_parent_dir_path,
                })
            })?;
        }
        let file_path = relative_path.to_path(config.meta.root_dir.as_str());
        fs::write(&file_path, &contents).map_err(|error| {
            GenError::WriteFile(WriteFileError {
                error,
                path: file_path,
            })
        })?;
    }
    Ok(())
}

const AUTO_GENERATED_COMMENT: &str = indoc! {"
    This file is automatically @generated by Mulan.
    It is not intended for manual editing.\
"};
