[book]
authors = ["Asqar Arslanov"]
language = "en"
multilingual = false
src = "src"
title = "Mulan Guide"

[output.html]
additional-css = ["theme/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"
